name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: cargo clippy
    - name: Build
      run: cargo build --verbose
    - name: Self tests
      run: cargo test --verbose
    - name: Test examples
      run: cargo run --bin tester examples/*
